version: '3.8'

services:
  postgres:
    image: postgres:15-alpine #
    container_name: webshop_db
    environment:
      POSTGRES_USER: user        
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webshop       
    ports:
      - "5433:5432"              
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: webshop_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" 
    depends_on:
      - postgres 